//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanBida
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanBida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BanBida()
        {
            this.HoaDon = new HashSet<HoaDon>();
        }
    
        public int MaBan { get; set; }
        public string TenBan { get; set; }
        public Nullable<int> MaLoaiBan { get; set; }
        public string TrangThai { get; set; }
    
        public virtual LoaiBan LoaiBan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDon { get; set; }
    }
}
