//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanBida.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_DoAnBanVeXeEntities : DbContext
    {
        public DB_DoAnBanVeXeEntities()
            : base("name=DB_DoAnBanVeXeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bus> Bus { get; set; }
        public virtual DbSet<DetailsTicket> DetailsTicket { get; set; }
        public virtual DbSet<Driver> Driver { get; set; }
        public virtual DbSet<OrderTicket> OrderTicket { get; set; }
        public virtual DbSet<Passenger> Passenger { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Route> Route { get; set; }
        public virtual DbSet<Seat> Seat { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Trip> Trip { get; set; }
        public virtual DbSet<UserAccount> UserAccount { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
    }
}
