//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanBida.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailsTicket
    {
        public int DetailsTicketID { get; set; }
        public Nullable<int> OrderTicketID { get; set; }
        public Nullable<int> TripID { get; set; }
        public Nullable<int> SeatID { get; set; }
        public Nullable<bool> IsBooked { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual OrderTicket OrderTicket { get; set; }
        public virtual Seat Seat { get; set; }
        public virtual Trip Trip { get; set; }
    }
}
