//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanBida.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trip()
        {
            this.DetailsTicket = new HashSet<DetailsTicket>();
        }
    
        public int TripID { get; set; }
        public Nullable<int> RouteID { get; set; }
        public Nullable<int> BusID { get; set; }
        public Nullable<int> DriverID { get; set; }
        public string DepartureLocation { get; set; }
        public string ArrivalLocation { get; set; }
        public Nullable<System.DateTime> DepartureTime { get; set; }
        public Nullable<System.DateTime> ArrivalTime { get; set; }
    
        public virtual Bus Bus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailsTicket> DetailsTicket { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Route Route { get; set; }
    }
}
