//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyQuanBida.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRoles
    {
        public int UserRolesID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> RoleID { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
